server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
       routes:
         - id: user-service
           uri: http://localhost:8080
           predicate:
             - Path=${app.api-prefix}/auth/**, ${app.api-prefix}/user/**
           filters:
             - StripPrefix=2
         - id: product-service
           uri: http://localhost:8060
           predicate:
              - Path=${app.api-prefix}/product/**, ${app.api-prefix}/category/**
           filters:
             - StripPrefix=2
