server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
       routes:
         - id: user-service
           uri: http://localhost:8080
           predicates:
             - Path=${app.api-prefix}/auth/**, ${app.api-prefix}/users/**
           filters:
             - StripPrefix=2
         - id: product-service
           uri: http://localhost:8060
           predicates:
              - Path=${app.api-prefix}/product/**, ${app.api-prefix}/category/**
           filters:
             - StripPrefix=2
         - id: profile-service
           uri: http://localhost:8081
           predicates:
              - Path=${app.api-prefix}/profile/**, ${app.api-prefix}/address/**
           filters:
            - StripPrefix=2
         - id: notification-service
           uri: http://localhost:8084
           predicates:
              - Path=${app.api-prefix}/api/notification/**
           filters:
             - StripPrefix=2    