server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
       routes:
         - id: user-service
           uri: lb://user-service
           predicates:
             - Path=${app.api-prefix}/auth/**, ${app.api-prefix}/users/**
           filters:
             - StripPrefix=2
         - id: product-service
           uri: lb://product-service
           predicates:
              - Path=${app.api-prefix}/product/**, ${app.api-prefix}/category/**
           filters:
             - StripPrefix=2
         - id: media-service
           uri: lb://media-service
           predicates:
             - Path=${app.api-prefix}/media/**
           filters:
             - StripPrefix=2
         - id: profile-service
           uri: lb://profile-service
           predicates:
              - Path=${app.api-prefix}/profile/**, ${app.api-prefix}/address/**
           filters:
            - StripPrefix=2
         - id: search-service
           uri: lb://search-service
           predicates:
               - Path=${app.api-prefix}/search/**
           filters:
               - StripPrefix=2
         - id: notification-service
           uri: lb://notification-service
           predicates:
              - Path=${app.api-prefix}/notification/**
           filters:
             - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1