server:
  port: 8084
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-node: localhost:9200
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: product
      auto-offer-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      string.json.trusted.packages: "*"
springdoc:
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    version: v1.0.0
    serverUrl: http://localhost:8082
    serverName: Test-searchService
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1