server:
  port: 8069
  servlet:
    context-path: /cart-service
spring:
  application:
    name: cart-service
  datasource:
    url: "jdbc:mysql://localhost:3306/cart_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

open:
  api:
    version: v1.0.0
    serverUrl: http://localhost:8068
    serverName: Cart Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
