server:
  port: 8080
spring:
  profiles:
    active: native
  applications:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-location: classpath:/configurations